### ISSUE TITLE
Deprecation message when loading dataset using `nilearn.datasets.fetch`

### ISSUE THREAD

**Issue by emilyemchen** [brainhack-school2020/abide-fmri#24]
See scripts for leave-site-out or group-k classifier for issue when loading dataset with the following code:

```
#Import modules for this step
from nilearn import datasets
import pandas as pd
import os
#Fetch data using nilearn.datasets.fetch
abide = datasets.fetch_abide_pcp(data_dir=/path/to/data),
                                 pipeline="cpac",
                                 quality_checked=True)

#Load phenotypic data into pandas dataframe
abide_pheno = pd.DataFrame(abide.phenotypic)

#Create array to hold unique site names
groups = abide_pheno["SITE_ID"].unique()
```

Receiving this warning message:  

```
VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)
```

Any idea what's going on here? Does not necessarily prevent script from running. 

@pbellec @surchs

**Comment by surchs** [comment]
Hi @emilyemchen: A [Deprecation Warning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) is intended for the developer of the code that is triggering the warning. The warning indicates that there has been a change in how a library should be called and that the code using this library should be updated to this new specification. 

The reason these warnings exist is so that developers and users get some advance notice of future changes that may break their current implementation. A bit like a public notice about a subway construction project: it's still running now, but please find another route for the future because it may break in a new version / at a later date.

As you have seen, it doesn't break you current script so you can ignore it if long term maintainability isn't your goal right now or if you don't plan on updating your environment in the near future. This is another reason why python environments / containerization can be so useful. In the future, some of your code may only work with the (then) older libraries you have used when you wrote it. Still having them around in an environment / container will save you a lot of debugging / updating.
